### ISSUE TITLE
I would like divs moving up to do so in front of other divs rather than behind.

### ISSUE THREAD

**Issue by Makdash49** [joshwcomeau/react-flip-move#118]
When I have a list of divs, and I move one from the bottom to the top of the list, it moves underneath the other divs until it reaches its destination.

The user is likely to have their attention on the div moving up and yet this is the div that is hidden from view.

I like how divs move to the bottom of the list.  They move down in front of the other divs.  I would like this for both divs moving up and divs moving down.  I would like the div that has the user's attention to be fully visible through the entire transition.

**Comment by joshwcomeau** [comment]
Mhmm, z-index ordering is something I've thought a bit about.

The thing is, it's actually kind of a hard problem. There's no such thing as 1 div moving; in the example you describe, if the div is moving up, all the divs _before_ that one are moving down by 1 unit as well. How should FlipMove decide which animation is the "important" one? What if 2 divs move up and 4 move down? What if they're shuffled?

I think this could be tackled in user-land, by simply increasing the z-index of the element(s) you want to float above the others. You could use the `onStart` hook to check if the element is the one you care about, and apply a style directly to the DOM node provided to the handler.

This could have performance implications, especially if your animation is interruptable (applying a z-index will cause a reflow, which is bad if the _previous_ animation is still happening). I would give it a try, though, if this is important for your application :)

Let me know how that works, or if my instructions aren't clear. If there are problems, I'll give the problem some thought, although I probably won't have the chance to implement a solution for a while.
