### ISSUE TITLE
Nested <FlipMove> lists don't animate properly

### ISSUE THREAD

**Issue by cameronhimself** [joshwcomeau/react-flip-move#12]
I have a structure like this:

    <FlipMove>
        <div class="section">
            <FlipMove>
                <div class="item">...</div>
                <div class="item">...</div>
                <div class="item">...</div>
            </FlipMove>
        </div>
        <div class="section">
            <FlipMove>
                <div class="item">...</div>
                <div class="item">...</div>
                <div class="item">...</div>
            <FlipMove>
        </div>
    </FlipMove>

(pretend everything has a unique key property)

The items animate correctly, but when a section is moved all of its child items animate as well, making for a confusing jumble of motion.

(Incidentally, in my use case items can be moved between sections. When that happens the item snaps into the new section with no movement animation (the sections do animate to expand/contract, however). I don't really expect this component to support that kind of functionality, but I figured I'd mention it.)

**Comment by joshwcomeau** [comment]
Hi Cameron!

A project I'm working on will require exactly this functionality, and I was hoping the nested FlipMoves would work. I'll take some time over the next few days to investigate, and hopefully there's an easy solution =)

As for having it animate between sections, that is functionality I spent an evening trying to implement. Ultimately it wound up being more complicated than I had hoped (just being able to shove one `<FlipMove>` at the top and then animating anything with a `key` property), and I didn't want to make the codebase so much more unapproachable for a feature nobody would need.

If I get a couple more requests for it, I'll take another crack at it. It would be awesome to have.

**Comment by IamNotUrKitty** [comment]
@cameronhimself  if I correct understand You,  problem with child animation (when section position is changed) can be solved with `shouldComponentUpdate`. Check this [demo](http://codepen.io/iamnoturkitty/pen/YqKgRw).

**Comment by cameronhimself** [comment]
@IamNotUrKitty I haven't tested your solution, but that certainly looks like it would work in my use case. The only problem I see is that it would involve adding a semantically irrelevant `ItemList` component. Not the worst thing in the world, but I'd prefer to have a clean `Section` -> `Item` hierarchy of components if possible. I'll definitely implement your solution if this issue isn't able to be solved. Thank you for looking into it!

**Comment by joshwcomeau** [comment]
@IamNotUrKitty interesting! 

Yeah, that's a good workaround, but really it shouldn't be necessary. I'm gonna see if I can find a way to account for it in the code base, but for now @cameronhimself, I would go with this solution.

**Comment by joshwcomeau** [comment]
Ok, so I've had the chance to dig into the problem, and it's non-trivial. Because I'm using transform: translate, the changes are always happening relative to the parent. If the parent is moving as well, it can't easily take into account it's parent's movement, so it overshoots.

The problem with the codepen provided with @IamNotUrKitty is it does not allow both child and parent to move at the same time. In my side project, I'm building a graph/nodes visualization and I need the nodes to move vertically in their parent while the parent moves horizontally.

I'm thinking a solution might be to allow a single axis to be specified per FlipMove. In the codepen provided by @IamNotUrKitty, the outer one only ever needs to move vertically whereas the children only ever need to move horizontally.

The syntax would look something like:

```js
<FlipMove>
  <section>
    <FlipMove limitToAxis='y'>
      <div className="child" />
      <div className="child" />
    </FlipMove>
  </section>
  <section>
    <FlipMove limitToAxis='y'>
      <div className="child" />
      <div className="child" />
    </FlipMove>
  </section>
</FlipMove
```

Even though you're specifying the child to only move on the Y axis, it would still move in both directions if the parent and child change at the same time.

@cameronhimself / @IamNotUrKitty, what do you guys think?

**Comment by joshwcomeau** [comment]
Also @IamNotUrKitty, I just realized I never thanked you for providing that codepen. Really appreciate how much effort you put into it :) thanks so much for your contributions to this project.

**Comment by cameronhimself** [comment]
I can't speak in general, but for my particular project this would be a perfect solution. My sections and items only need to move vertically. Thanks for looking into it.

**Comment by cameronhimself** [comment]
sorry, accidentally clicked close and comment!

**Comment by joshwcomeau** [comment]
Hahaha no problem :) I've implemented that solution and it works well, but I want to refactor it and write some tests. Will likely push a new version with those properties in the next couple days :)

**Comment by IamNotUrKitty** [comment]
@joshwcomeau you implement solution with `limitToAxis` prop? 

I have some other idea with this problem, what if we will be calculate element position relative to his parent, it solves all problems and get some more abilities. Something like sections have items in grid view, and grid can be reordered.

 I implement it and make one more [demo](http://codepen.io/iamnoturkitty/full/grOvMB/).

If you think that interesting check this [commit](https://github.com/IamNotUrKitty/react-flip-move/commit/c14d987ef4290cff11fae674da32385e2a276211). I can make PR, but now i have no idea how it can be test coverage.

**Comment by joshwcomeau** [comment]
@IamNotUrKitty awesome! I was actually just playing with this today trying to get enter/exit animations working. Didn't realize it could work for this as well!

Feel free to submit a PR. Don't worry about specific test cases for this. If it passes the generalized case, that's good enough for me.

**Comment by joshwcomeau** [comment]
Just asked a quick question on #13 - Will merge in as soon as I understand the Math.abs thing!

**Comment by joshwcomeau** [comment]
@cameronhimself this functionality is enabled in v1.2.0. There is no need to change the API; if you upgrade to that release, everything should work automatically :)

**Comment by cameronhimself** [comment]
works beautifully for me! thanks @joshwcomeau and @IamNotUrKitty
