### ISSUE TITLE
Beefing up the customization of the enter and leave animations

### ISSUE THREAD

**Issue by deibeljc** [joshwcomeau/react-flip-move#128]
Currently I have requirements that require a slightly more complex animation case than is currently supported. I have to have a linear delay stagger (supported) but also an "exponential" (more on this later) duration stagger. Another thing that I needed was to have separate timings for opacity and transform. You can see it in action at http://0cf638e7.ngrok.io/ (very temporary link!). Currently I am thinking that this might be a nice addition to flip-move

"Exponential" duration
---
What "exponential" duration stagger actually means is is duration per element increases. I am using the term exponential because my motion designer called it that!

So the duration would look like

- List
  - Item : duration 350ms
  - Item : duration 400ms
  - Item : duration 500ms
  - Item : duration 550ms
  - Item : duration 550ms | We defined a hard cap at 550ms so it doesn't get stupid long for lists

The API I have built in currently looks like this for the exponentialDuration

```js
const customEnterAnimation = {
  from: { transform: 'translateY(100%)', opacity: 0 },
  to: { transform: 'translateY(0%)', opacity: 1 }
}

const customExitAnimation = {
  from: { transform: 'translateY(0%)', opacity: 1 },
  to: { transform: 'translateY(-100%)', opacity: 0 }
}

<FlipMove
  staggerDurationBy={this.state.stagDurBy}
  onFinishAll={this.handleFinishAll}
  staggerDelayBy={this.state.stagDurBy}
  exponentialDuration={true}
  exponentialDurationCap={500}
  enterAnimation={customEnterAnimation}
  leaveAnimation={customExitAnimation}
  duration={350}
  easing={this.state.easing}
>
```

My code changes are [here](https://github.com/deibeljc/react-flip-move/blob/finetune-animation-control/src/dom-manipulation.js#L220). And they are certainly not final as the API is totally arbitrary currently

Separate Timings
---
For this I needed to define a custom duration for both the opacity and the transform property because the opacity needed to be done in a flat 100ms whereas the transform had 350ms+ (depending on the exponential stagger) to finish. In order to do that I decided that the best way to succinctly send this info in would be to describe it in an object that is sent down via props.

```js
const customDuration = {
  transform: {
    duration: 350,
    stagger: true
  },
  opacity: {
    duration: 100,
    stagger: false
  }
}
```

Right now I am sending it down via the prop customDuration but I think it probably makes more sense to just have duration accept an object.

When adding that change I dealt with not cleaning up the child element by waiting for the longest duration animation to complete. See [findLongestTransitionProperty](https://github.com/deibeljc/react-flip-move/blob/finetune-animation-control/src/FlipMove.js#L315) and my changes in the [transitionEndHandler](https://github.com/deibeljc/react-flip-move/blob/finetune-animation-control/src/FlipMove.js#L344)

P.S. Sorry this issue turned into a giant post!

**Comment by joshwcomeau** [comment]
Heya,

So, this is neat - it's great to see you add in the functionality missing for your use-case.

I don't think I'd like to implement them in Flip Move though. I already feel like Flip Move's internal complexity is too high, and the cost of maintaining these additional usecases aren't worth the relatively small number of users who need them.

I think Dan Abramov [summed it up perfectly](https://github.com/jlongster/prettier/issues/40).

I'd encourage you to keep working on your fork :) I don't anticipate any major changes to this project for a while (at some point I'd like to rewrite using Web Animations API, but it'll be a while until browser support is decent).

**Comment by deibeljc** [comment]
Cool links, thanks for showing me that! As a quick question -- do you expect any breaking changes that will need addressed when react fibre is released? I only ask because I want to minimize my team's upgrading pain if possible

**Comment by joshwcomeau** [comment]
@deibeljc excellent question - I don't _think_ so. I've read that the only potential consequence is that `componentWillMount` can be called multiple times. FlipMove doesn't use that lifecycle hook though.

As long as Fibre doesn't try to incrementally render part of the children, which it shouldn't, we shouldn't have any issues. That said, this is very much a guess based on what I currently know.
