### ISSUE TITLE
[Question] filtering large data set with virtualization 

### ISSUE THREAD

**Issue by MarcMagnin** [joshwcomeau/react-flip-move#131]
Hi,

I was wondering if that could be possible to intergrate react-flip-move with some virtualization such as:
https://bvaughn.github.io/react-virtualized/#/components/Collection

The idea would be to present a lot of items (let say 30K images to represent) and been able to virtualize them (not rendered outside of the view) and add the nice and smooth filtering animations such as https://www.kunkalabs.com/mixitup/.

Or do you already have a nice way to handle such a data set ?
Many thanks!

**Comment by joshwcomeau** [comment]
Hey there,

Yeah, that won't work, lol.

I think it would be possible to build a solution that could handle it, but it would need to be custom-built. I can think of a few things that would make it challenging, but I think it's possible in theory.

I checked with react-virtualized and they don't have any built-in solutions for animations. Brian Vaughn describes a potential solution [here](https://github.com/bvaughn/react-virtualized/issues/249), but you'd need to build something non-trivial.

Best of luck!
