### ISSUE TITLE
Accept non-string as typeName + rename typeName to component

### ISSUE THREAD

**Issue by lumio** [joshwcomeau/react-flip-move#135]
FlipMove currently doesn't accept components as typeName. But I would love to use `styled-components` with it.

**Comment by joshwcomeau** [comment]
Hm. So, the reason `typeName` exists is just to prevent illegal DOM structures (like, if you want your animated items to be `li`s, the wrapping element needs to be a `ul` or `ol`).

The `<FlipMove>` wrapper is meant to be as invisible as possible; when React 16 comes out, I'd love to pen a version that doesn't need a wrapping div (Fiber will support returning arrays of elements, so this should be possible!).

I would just treat `<FlipMove>` as an invisible layer:

```js
const Wrapper = styled.section`
  padding: 4em;
  background: papayawhip;
`;

return (
  <Wrapper>
    <FlipMove>
      ...
    </FlipMove>
  </Wrapper>
);
```

That said, looking at the code, I don't see any reason that you couldn't supply a component to `typeName`? The propTypes will complain, sure, but it _should_ still work; the code just calls `React.createElement` and passes the typeName as the first arg.

If it works, I'm happy to update the propTypes to allow for components. I wouldn't want to rename it, though; It would require a major version bump, and given that I'm hoping to abolish the wrapping element altogether soon, it wouldn't make sense.

Let me know!

**Comment by lumio** [comment]
I see! Well, I think just changing the propType won't do, since flip-move will break when trying to call `node.getBoundingClientRect`. Which makes sense, since I'm appending a react component (in this case a styled component).

As for React 16: Finally ❤️😀

**Comment by joshwcomeau** [comment]
Ahh, right, yeah. We need to get the parent's boundingBox so that we can get relative boxes for the children.

So yeah, I'd just nest the FlipMove inside your styled component :+1:

**Comment by frol** [comment]
I am using React-MD, which has custom tables components and while using plain `<table>`/`<FlipMove typeName="tr">` works fine, I cannot use the custom `TableRow` component, and given the fact that it is a table and there is no way to simply wrap things with an extra div, I would love to hear how I can workaround this limitation (I bumped into the `node.getBoundingClientRect`)

**Comment by frol** [comment]
I have worked around the missing `node.getBoundingClientRect` on the react component by defining it there. Basically, you may either patch or inherit the component:

```javascript
import { findDOMNode } from 'react-dom'

TableBody.prototype.getBoundingClientRect = function() {
  return findDOMNode(this).getBoundingClientRect()
}
```

```javascript
import { findDOMNode } from 'react-dom'

class CustomTableBody extends TableBody {
  getBoundingClientRect() {
    return findDOMNode(this).getBoundingClientRect()
  }
}
```

**Comment by joshwcomeau** [comment]
Clever! Yeah, that makes sense. As long as the supplied component "behaves" like a DOM Node in this regard, Flip Move will happily accept it.
