### ISSUE TITLE
Replace PropTypes with Flow

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/react-flip-move#139]
I've been using Flow on other projects, and I like it.

If anyone wants to lead this change, lemme know. Otherwise I'll likely tackle it in the next couple weeks.

**Comment by Hypnosphi** [comment]
I think I can do that

**Comment by Hypnosphi** [comment]
OK, there is a problem.

[Here](https://github.com/joshwcomeau/react-flip-move/blob/master/src/prop-converter.js#L127) `propTypes` keys are used in runtime to determine which props should be delegated to the DOM element. This isn't really achievable with static typechecking.

Would it be OK to keep an array of FlipMove-specific prop keys in a separate variable and keep it in sync with props typings?

**Comment by Hypnosphi** [comment]
OK, I think I found a better solution: https://github.com/joshwcomeau/react-flip-move/pull/145/files#diff-ecdb6cdeb1de0c9f5925708a2be17e73R122

**Comment by joshwcomeau** [comment]
Right, yeah that's tricky.

I like your solution, though! 

I'm wondering if we ought to keep some PropTypes as well, as a helpful indicator to developers using FlipMove. Flow is great for contributors to FlipMove, but it offers no runtime notifications for developers who may be using FlipMove incorrectly.

I don't think it's that big a deal - we already log warnings when developers do things they shouldn't (eg. using SFCs). Just wanted to bring it up in case anyone else had opinions :)

**Comment by Hypnosphi** [comment]
I'll make another little PR which would just replace `React.PropTypes` with `prop-types` package then
