### ISSUE TITLE
Merge two wrapping component to one

### ISSUE THREAD

**Issue by valentinvichnal** [joshwcomeau/react-flip-move#14]
Hi, how should I merge 2 component when both component must be the parent of the child List elements to perform the actions on them?

Take for example, import 2 different Animate react library, both make some animation on a list of rendered items.

```javascript
import Animate1 from 'react-animate1';
import Animate2 from 'react-animate2';
 ```

The items I wish to apply the animations to:
```javascript
renderItems() {
  return items.map(item=> <Item key={item.id} />);
}
 ```

Best way to apply both to the items?
```javascript
<Animate1>
  <Animate2>
    {this.renderItems()}
  </Animate2>
</Animate1>
 ```

This code will break Animate1, it won't be applied to the items inside the Animate2.

Any idea how to do this, maybe modifying the Animate1 source code to apply the effects to the second-level child elements?
Is there a good approach to solve this problem without altering the wrapper components source code, perhaps creating a new component and compose the two Animate wrapper component in some way?

**Comment by joshwcomeau** [comment]
Yeah, I spent a night looking into the feasibility of making Flip Move work recursively. It worked, sorta, but it made a mess of the code and had performance implications (which could be alleviated by specifying a max "depth" to go, so you could limit it to grandchildren).

Flip Move does introduce a wrapping <div>, so it would not be composable out-of-the-box.

Can you provide a more real-world example of what you need? Are you talking about nested Flip Moves, or about combining it with another animations library that only works on children?

**Comment by valentinvichnal** [comment]
It is true two animate wrapper component on a list is not a frequent task,
my problem is to combine an outer InfiniteScroll component with the nested FlipMove which contains the list items. It is somewhat related to your other issue #8 , in this case there are no style-only div elements but React.js componenst.

Many react libraries wants to impact direct child list elements only, so I am looking for a more general way to deal with this problem, maybe you know a framework to work with these double-nested components?

**Comment by joshwcomeau** [comment]
Yeah, I hear you. I'm afraid I don't have an easy solution to the problem.

Infinite scrolling can probably be done manually, though. Not sure you need a component for that :)

Closing, because I don't intend on solving this problem with this project. Sorry!

**Comment by valentinvichnal** [comment]
No worries! I have created a simple scrolling manually, this is enough for now and it works with flip-move.
