### ISSUE TITLE
Shared element transition across routes?

### ISSUE THREAD

**Issue by shubhamsizzles** [joshwcomeau/react-flip-move#15]
FLIP animation techniques were first used in card-expanding animations in the chrome dev summit site. 
Is there any way to animate cards across react routes using this library?
Something like shared element transitions on Android. 
eg. https://youtu.be/94q_8nOiGKk?t=27s

**Comment by joshwcomeau** [comment]
Afraid not; the aim of this library is much more specific, to animating list re-orderings (basically using the FLIP technique to do what Ryan Florence's Magic Move library does, with a few small bells and whistles).

A generalized FLIP animations library is not a bad idea, but it's not this project :)

Best of luck!
