### ISSUE TITLE
Flip Move Messing Up Grid

### ISSUE THREAD

**Issue by BlueBlazin** [joshwcomeau/react-flip-move#167]
I have a grid of boxes which is aligned using 
`display: flex;
  flex-wrap: wrap;
  justify-content: space-between;`

Unfortunately, when I use FlipMove, the boxes are being stacked vertically in a single column and their height is also increased. 

Any suggestions on how I might go about fixing this?

**Comment by Hypnosphi** [comment]
do you pass those styles to `FlipMove`? Can you set up an example at jsfiddle or somewhere else?

**Comment by stolinski** [comment]
I'm getting the exact same thing. `display: flex; flex-wrap: wrap; justify-content: space-between;` are the only properties on my FlipMove container.

**Comment by joshwcomeau** [comment]
Yeah, without seeing a live example, it's hard to diagnose.
