### ISSUE TITLE
Possibility to keep own ref to the particular items or make accessable

### ISSUE THREAD

**Issue by aight8** [joshwcomeau/react-flip-move#17]
I added refs to the items to access it in my component, because I need the nodes for scrolling reason. I need the DOM node object of them.
Currently there is no way to access the underneath cloned items. Because of the propConverter decorator it's not possible to access the FlipMove refs and fetch a particular item component.
I tried with the react-shuffle library and there it's possible and everything works well (btw. inclusive enter/leave animation)
I don't know exactly how to solve this problem, because of the decorator I lose all possibilities to access the FlipMove object which could implement an getChild(childKey) method for use cases like this.

Any idea how to solve this?

**Comment by joshwcomeau** [comment]
So, I'm a little annoyed by the dig about enter/leave animations. Totally unrelated to this issue, doesn't exactly make me want to help you with your problem.

It might be possible to expose the ref, but I'm not thrilled with the idea of complicating the API for such an obscure use-case. Nobody else has needed access to the refs, and I'm trying to keep the footprint as minimal as possible.

If you look at the commit history, the decorator's introduction was pretty recent. You could fork it, "undo" the decorator by putting its logic back in the component itself, and add whatever method you need to access the ref. I wouldn't be interested in merging that in, though.

**Comment by aight8** [comment]
Yep I'm currently forked this library and implemented the method w/o the decorator - I don't see 100% why a decorator is needed since there is no encapsulation benefit and the type conversation is not the standard React way. The problem can be solved to remove the decorator again OR just decorate the FlipMove object in a separte file (that will be used in index.js) so people can use the plain FlipMove object.

The problem is that there is no way to access the item nodes at all - not even with a workaround atm. Maybe it's not a popular feature but an important architecture decision.

**Comment by joshwcomeau** [comment]
Yeah, I'm just using the decorator to make the main lib code more readable and simpler. Because props are immutable inside the component, I needed a higher-order component to pre-format them. 

What is the "standard React way"? 

Yeah, I suppose while this is a really narrow problem, there may be many similar narrow problems that can be solved by making the base class available.

If you have an idea for how to make the nodes available without cluttering up the base class code, I'd like to discuss. Reopening issue.
