### ISSUE TITLE
Animation works on array.filter() but not on array.swap()

### ISSUE THREAD

**Issue by Okami92** [joshwcomeau/react-flip-move#178]
Hi, hope to find help with my case.

In my application, I have a list of 7 position absolute elements in container. They are posts, shared by users. Every one of them has person name and message title. The one in the middle also has expanded message container. When you click on one of the list items, it swaps positions with one in the center and expands text. The problem is that elements swap, but animation doesn't trigger. When deleting clicked elements with filter, animation works on it. Tried a lot of different things already, including described issues here, but nothing works. Please help. Here is my code. I left only part which represents this case:

P.S. 'text[0]' is unique for every element.

```
Array.prototype.swap = function (a, b) {
  if ( b >= this.length || b < 0 ) return this;

  let temp = this[a];
  this[a] = this[b];
  this[b] = temp;
  return this;
};

flipListItem = (index) => {
    this.setState({
      data: this.state.data.swap(0, index)
    })
  };

  renderSlides() {
    const { data } = this.state;

    if (!data) {
      return null;
    }

    return (
      <div className="carousel__slide">
        <FlipMove>
          {data.map((item, i) => {
            const { name, subclaim, text, timestamp } = item;
            return (
              <div className="message" key={text[0]} onClick={() => this.flipListItem(i)}>
                <h4>{name[0]}</h4>
                <p>{subclaim[0]}</p>
                {i === 0 ? <div className="message__text">{text[0]}</div> : null}
              </div>
            )
          })}
        </FlipMove>
      </div>
    )
  }

  render() {

    return (
      <div className="carousel">
        {this.renderSlides()}
      </div>
    )
  }
```

**Comment by joshwcomeau** [comment]
Hey there,

Sorry about the delay!

Looked over it quickly and nothing jumps out at me... Maybe the fact that `swap` doesn't return a new array?

What if you did:

```
Array.prototype.swap = function (a, b) {
  if ( b >= this.length || b < 0 ) return this;

  const workingCopy = [...this];

  let temp = workingCopy[a];
  workingCopy[a] = workingCopy[b];
  workingCopy[b] = temp;

  return workingCopy;
};
```

My thinking is that maybe because the array itself isn't changing, maybe something isn't updating as it should. The fact that `filter` works lends credence to this idea.

Let me know! If it doesn't work, could you re-create the issue on codesandbox.io or similar?

**Comment by joshwcomeau** [comment]
Closing since I haven't heard back. Feel free to follow up!
