### ISSUE TITLE
Add code formatter to deal with code styling

### ISSUE THREAD

**Issue by tobilen** [joshwcomeau/react-flip-move#181]
The most popular one being https://github.com/prettier/prettier, which is what i would prefer.

if nobody volunteers, i'll take a look at it this weekend. maybe throw in a couple extra eslint plugins for good measure :)

**Comment by joshwcomeau** [comment]
:+1: Prettier works for me! All for adopting community standards.

Happy to discuss additional ESLint rules! Are there any specifically you had in mind?

**Comment by tobilen** [comment]
https://github.com/ivx/eslint-config-ivx/blob/master/index.js those are the ones i like using

**Comment by joshwcomeau** [comment]
Getting a 404 :( is that repo private?

**Comment by tobilen** [comment]
it was. i changed it
