### ISSUE TITLE
Animation not working 

### ISSUE THREAD

**Issue by dsslimshaddy** [joshwcomeau/react-flip-move#188]
https://www.webpackbin.com/bins/-KtqTYBCgNDqG0bDeDNA

Did a quickstart from Readme. doesnt works atall

**Comment by Hypnosphi** [comment]
You use index as key, so `FlipMove` thinks that all the children stay on their position (item with key `0` is still the first, `1` is the second etc.). Try using something other as a key, e.g. `name` field: https://www.webpackbin.com/bins/-KtsMYuzFa9E_3xIG5LW
