### ISSUE TITLE
Temporarily disable animation

### ISSUE THREAD

**Issue by mauriciosoares** [joshwcomeau/react-flip-move#19]
Hey, is there a way I can temporarily disable all the animations from `FlipMove`? like a property or something like this: `<FlipMove disableAnimations={true} />`.

The reason I need to do this is that there are some situations that I don't want my components to be animated, and even if I pass `duration="0"`, it still flashes a little bit, like the animation happens extremely fast, but still I can see it.

Thanks!

**Comment by joshwcomeau** [comment]
@mauriciosoares, this is a good point!

I just fixed this, by adding a `disableAnimations` boolean prop. v1.4 now includes this property :)

Let me know if you have any issues!

**Comment by mauriciosoares** [comment]
Thanks @joshwcomeau!! that'll help me a lot.

Well, my example. Consider I have a list of items, and I can sort/edit these items.

When I'm sorting the items, it has a smooth animation, which is great! but when I click in the edit button, it opens a form inside the small cell, and it occurs an animation with the cell "opening", but the animation kinda breaks...

Perhaps this poor drawn picture will illustrate what I mean:

![untitled-1](https://cloud.githubusercontent.com/assets/2321259/14303275/a3ca361c-fb7f-11e5-8b79-6229c4e5ab8a.jpg)

(Don't pay attention on my photoshop skills, hahahaha)

**Comment by mauriciosoares** [comment]
Just to let you know, the `disableAnimations` property works flawlessly. And solved my problem!

Thanks man.

**Comment by joshwcomeau** [comment]
Awesome! Glad to hear it helped, and thanks so much for the thorough example =)
