### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [joshwcomeau/react-flip-move#197]
Hi
We would like to host your library on [cdnjs](https://github.com/cdnjs/cdnjs/issues/9564)
Could you please tell us what file should be hosted? 
Thanks

**Comment by joshwcomeau** [comment]
Hey there,

So, I don't have the built files checked into source control (makes for really messy PRs).

They're published via NPM with the following paths:

- `dist/react-flip-move.js`
- `dist/react-flip-move.min.js`

I love cdnjs! Let me know if I can do anything else to help :)

**Comment by sashberd** [comment]
@joshwcomeau Thanks for your feedback.
I saw dist folder on npm from 0.2.0 version. What about older version 0.1.0~0.1.4, what files should be hosted from them?

**Comment by joshwcomeau** [comment]
@sashberd ah, do we need to go that far back? We've had dozens of releases since then, and truthfully I was still figuring out OSS releases (this was my first OSS project!). I wouldn't trust the code back then, and I'm not surprised to hear that dist files weren't included (I probably didn't think to include a dist until 0.2.0)

**Comment by sashberd** [comment]
@joshwcomeau Usually, we have to host all version. However, if the author says that those versions are not relative and not in used at all users for this library, I suppose we could not host them.
@PeterDaveHello Can we disregard this versions by author suggest?
@joshwcomeau what about second question about version 0.1.5~0.1.7, can you add them to the NPM?

**Comment by PeterDaveHello** [comment]
I'm fine with that.

**Comment by sashberd** [comment]
@PeterDaveHello Thanks
@joshwcomeau Waiting for your answer/

**Comment by joshwcomeau** [comment]
Awesome, thanks!
