### ISSUE TITLE
Now with React 16, is it possible to render children without the wrapper?

### ISSUE THREAD

**Issue by MrSauceman** [joshwcomeau/react-flip-move#200]
In certain circumstances, wrapping the children with a div or anything else can cause issues with css.  Currently I am using a css package that uses direct children selectors `>` and the flip move wrapper causes issues with this.  The css is difficult to change because it's extensive and it's in its own package.

Is it possible to create an option to not wrap the children, now that React 16 allows rendering of arrays?

**Comment by tobilen** [comment]
ask (for cool things) and ye shall receive: https://github.com/joshwcomeau/react-flip-move/pull/201
