### ISSUE TITLE
Animate nested list items

### ISSUE THREAD

**Issue by Tsourdox** [joshwcomeau/react-flip-move#207]
Thx for this amazing component!

I'm curious to know if it is possible to animate when moving an item from a nested list to another, like this:

```
<FlipMove>
  <div key="list-a">
    <div key="a">Banana</div>
    <div key="b">Orange</div>
  </div>
  <div key="list-b">
    <div key="c">Apple</div>
  </div>
</FlipMove>
```

If let's say "Orange" was moved to list-b next to "Apple".

Or possibly group multiple FlipMove components together, something like this:

```
<div>
  <FlipMove group="fruit-list">
    <div key="a">Banana</div>
    <div key="b">Orange</div>
  </FlipMove>
  <FlipMove group="fruit-list">
    <div key="c">Apple</div>
  </FlipMove>
</div>
```

**Comment by tobilen** [comment]
tricky. but maybe there is an easier solve for your problem. why do you need to keep the elements in separate lists?

**Comment by Tsourdox** [comment]
The list is based on groups, but I'll probably change to list to a single one and just make it look like groups with css. Thx!
