### ISSUE TITLE
Function onFinishAll is never called

### ISSUE THREAD

**Issue by Tsourdox** [joshwcomeau/react-flip-move#209]
This is how I'm using it.
```
<FlipMove className="ui horizontal list" duration={300} onStartAll={this.onStartAll} onFinishAll={this.onFinishAll}>
   {this.items}
<FlipMove>
```

[onStart, onStartAll, onFinish] works as expected.
Using version 2.9.1

**Comment by joshwcomeau** [comment]
Hm, sorry about that! Thanks for the heads-up! 

Don't have a ton of time on my hands for this ATM, PRs welcome!

**Comment by tobilen** [comment]
i'll take a look at it at the end of the week. might also use it to do some dom cleanup, which hopefully prevents some more edge cases with nodes not being removed

**Comment by tobilen** [comment]
tested this in chrome/ff/ie11 with v2.9.10 as well as 2.9.1 . handler is being invoked correctly.

@Tsourdox if the problem persists, im going to need a reproducable code snippet (for example a [codesandbox](https://codesandbox.io/s/new))

**Comment by Tsourdox** [comment]
I believe I tested it in Safari but I'll se if I can test it again and se if the issue was on my behalf.

**Comment by tobilen** [comment]
safari (11) works as well:
![image](https://user-images.githubusercontent.com/8217788/34650051-7d958f2a-f3ba-11e7-97dc-4bc39f00550f.png)

**Comment by Tsourdox** [comment]
Tested it and it doesn't fire in any browser. I'm using FlipMove together with react-dnd but even if I remove that code the problem persists. I'll try and update to the latest version and se if that changes anything. At the moment I don't need the event so I'm good for now. Thx for looking in to it!

**Comment by tobilen** [comment]
Ok then, closing this issue.
It could be a problem with another library stopping propagation of events, but i'm just speculating here. If you manage to reproduce the problem, just reopen it.
