### ISSUE TITLE
Prop to Determine Pre-set Translations

### ISSUE THREAD

**Issue by marcus433** [joshwcomeau/react-flip-move#21]
Regarding "Existing transition/transform properties will be overridden", for the present what if react-flip-move checked for a prop on the children for example `translate3d={[x, y, z]}`. I believe this would be a valid solution for now as the user most likely will know the translations of their elements before hand. It also saves the need to parse existing CSS properties which may lessen the animation performance. For items that already have a `translate3d` prop I propose 2 custom options for the parent container stating what prop to transform from and whether to take into account transforms at all. Let me know what you think, I'd be happy to contribute to the implementation of this!

Also, great work on the library, I absolutely love it.

**Comment by joshwcomeau** [comment]
Hi Marcus!

In general, I'm a fan of keeping as small an API footprint as possible. I like the spirit of what you're proposing, but I don't like the idea of needing to track half a dozen new properties on the children. It's also a bit mind-bending; took me a couple read-throughs to understand what you meant.

I think the ideal solution is just to compare the currently-applied styles, and "diff" between what they are now and what they need to be.

For example, if an item has a user-specified `transform: rotate(10deg)`, and FlipMove determines that the item needs to shift it up by 20px, we could combine them into `transform: rotate(10deg) translate(-20px, 0)`. 

Another example, if the user specifies a 'transform: translate(10px, 0)` and we need to shift it up by 20px,we'd do the math and wind up with `transform: translate(-10px, 0)`.

This would require a mini-parser implementation that is able to understand `translate`, `translateY`, and `translateX`, and get the difference between the currently-set props and our computed what-needs-to-change props. 

As for performance, I'm not too concerned; we actually already are reading/writing to the node's `styles`, without any noticeable problems. That said, I could be totally wrong; this _is_ a performance-sensitive module, so we'd need to test it.

It doesn't strike me as a super-urgent feature, but it'd certainly be nice to have. If you'd like to take a crack at solving this problem, you're more than welcome to!

**Comment by marcus433** [comment]
Alrighty, sounds good! I'll look into it further. I'm quite interested in achieving this as it will allow support for virtual scrolling implementations!

**Comment by joshwcomeau** [comment]
👍 . Let me know if you have any questions about the source code.

**Comment by marcus433** [comment]
Alright sounds good! So far i've got the parser done. Still need to add matrix support however. It can be seen over at [TransformParser](https://github.com/marcus433/TransformParser/tree/master). I plan to have it done and a pull request ready in the next day or 2 :-).

**Comment by joshwcomeau** [comment]
Cool. I like the idea of the parser being its own module, since it's a totally separate concern. Plus, other projects might benefit from it! Seems like a general problem that surprisingly hasn't been solved yet, as far as I can see.

That code is very terse, though. It's impressive, but it's hard to decipher. Totally up to you, but maybe we could make the variable names more semantic? Really, as long as there are good tests, terseness is OK :)

Thanks for your help! Will be awesome to have this functionality. I'm working on enter/exit animations this weekend and it's turning into a really hairy problem, so it's good to know that other people are interested in this module!

**Comment by marcus433** [comment]
Indeed, the code is terse. I ran it through google closure as it generally makes some good optimizations which is important for this. I'm planning to comb through it and write it all in clean ES6 though. Looking forward to enter/exit animations!

**Comment by marcus433** [comment]
I should implement this in componentWillReceiveProps and getPositionDelta, correct?

**Comment by marcus433** [comment]
I haven't gotten around to writing tests yet, I have however tested it and everything is working! You can check it out over at [marcus433/react-flip-move](https://github.com/marcus433/react-flip-move). Also, I ended up not having a module for the parser as it's too much overhead to have a separate module and I ended up having to do a few specific things in it that wouldn't be required for non react-flip-move uses.

**Comment by joshwcomeau** [comment]
Awesome! Will check it out shortly. Thanks :)

**Comment by marcus433** [comment]
I've been working on getting the enter/leave animations to work with pre-existing translations however i've ran into a problem due to the new top, left, right properties. Why is this being used rather than a translate to the top/left/right position like before?

**Comment by marcus433** [comment]
Never mind, it has to do with something else.

**Comment by joshwcomeau** [comment]
Appreciate your speediness! I'm hoping to launch 2.0 tomorrow morning (still need to repair the tests, and make sure it works in a couple of less-isolated situations).

To answer your question, essentially to get enter/exit animations to work, I need to take exiting elements out of the flow. Ideally we want it to appear exactly the same, but for the browser's rendering engine to ignore it when calculating layout. The easiest way I've found is to give it `position: absolute`, but the trouble is that it tends to move things about, especially if multiple items are being removed at the same time.

So, I use the stored boundingBox to figure out where it is, relative to its parent container, as well as `getComputedStyle` to extract (and then counter-act) any margin. This way, the item stays exactly where it is when it's set to position: absolute.

Hope it helps!

**Comment by joshwcomeau** [comment]
@marcus433 I had another fantastic idea, for a problem your work could solve.

Right now, when an animation is interrupted, items "snap" to their end position and start animating from there. This is because the rendering engine doesn't take `transform: translate` into account when it figures out where everything is at first.

A better solution would be to save its initial current "transform" property, and apply that to the item's computed new property.

Anyway, this stuff is complicated and I don't wanna overburden you. Just a thought for the future :)

**Comment by marcus433** [comment]
@joshwcomeau Sure! I'll look into it later this week :-)

**Comment by marcus433** [comment]
Been a bit busy. Should be able to get it done either today or tomorrow

**Comment by joshwcomeau** [comment]
No worries :)

**Comment by marcus433** [comment]
Hey @joshwcomeau in your latest `flexVertical` branch commit is there support for setting the transition back to the original after flip-move has reached it's desired position (finished animating)?

**Comment by joshwcomeau** [comment]
Hey @marcus433,

That branch doesn't really handle that; it does two things:

* For items that are entering/leaving, it also calculates their transition. Initially, it only bothered if the items were NOT entering/leaving
* The enter/leave presets were modified to set translate to 0 at the end. This helps ensure that both the start and end positions are respected (I think; I dont remember off the top of my head why this change was required)

**Comment by joshwcomeau** [comment]
Hi @marcus433!

Just a quick check-in; are you still interested in pursuing this? It's ok if you aren't :) I'm happy to give it a shot.

Let me know!

**Comment by marcus433** [comment]
Hey @joshwcomeau,

Apologies for the late reply. Yeah I'll definitely pick up the pace on pursuing this :-). I haven't had much free time recently. If you could find a way to persist the original translation after the flip-move is done that would make it way easier for me to get this working. I'd do it myself but it will take longer as I obviously don't have as much knowledge about the setup as you do :-)

- Marcus

**Comment by joshwcomeau** [comment]
Hey @marcus433,

Sorry I never replied to your last comment!

So it turns out I kinda need to solve this problem for #45. I realized that probably the best way to do this is to convert all transforms to matrices. I'm still learning how they work but it _sounds_ like you can combine matrices by just multiplying them together.

The steps that I'm seeing are:

* Create a parser that can turn any CSS transform property (rotate, scale, skew, translate, etc) into a matrix (Turns out this exists: https://www.npmjs.com/package/css-to-matrix. May or may not be worth using)
* Add a method that is capable of combining matrices into one, for when we want to augment an existing matrix with the offset needed for FlipMove
* Find a way to persist the "original" transformation, to use as the end-goal (instead of resetting to 0)
* Make sure it can be used with enter/exit animations as well as position shifting.

I have some free time this weekend so I may look into this a bit. 

Let me know what your thoughts are!

**Comment by marcus433** [comment]
Hey @joshwcomeau, 

It's fine!

So what we could potentially do is get computedStyle and parse that matrix as it takes into account all transformations. I have done this here: https://github.com/marcus433/react-flip-move/blob/master/src/helpers.js#L40. In the CSS3 Matrix the modification of x, y positions is rather easy as they are simply attributes of the matrix, however rotations etc require calculation. I have thought of a way to avoid this:
- We retrieve the original matrix before any of our transformations have been applied. This is stored as an "Initial State" of sorts.
- Then we apply the user's animation in conjunction with the matrix.
  The matrix portion of the transformation will be calculated with the helper I noted above as it will take into account the current position flip-move needs to be at. The enter/exit transform is then layered on top as seen here:
  `transform: rotateX(90) matrix3d(...)`
- To remove the user transform when it is done animating we simply plug the saved state into the helper along with the position we need it to be at and it will return the new transform.

The benefits of this approach are we take advantage of the native CSS parser, it will work with literally any transform, and it is much simpler.

Let me know what you think!

- Marcus

**Comment by joshwcomeau** [comment]
Awesome. You're totally right about relying on the native CSS parser, that's a great idea.

This looks really great! Will work on persisting the original transform props; pretty busy this week but hopefully I'll find some time soon :)

**Comment by marcus433** [comment]
Hey @joshwcomeau 

Any news on this issue? I'm available to contribute to it again :-)

**Comment by joshwcomeau** [comment]
hey @marcus433,

I have not found the time, and you are more than welcome to pick this up again :)

**Comment by marcus433** [comment]
I have an idea that may make more sense than checking the DOM styles. What if a prop can be provided to FlipMove that is a function for determining external offsets. Eg if a transform is already applied the component using FlipMove likely knows about it and thus by passing both the `child` and `index` in `computeInitialStyles` to the function can return its offset.

Ex (example describes a situation in which a virtual scroller places elements 90px apart using transform)
```
<FlipMove offsetPosition={ (index, child) => {
    return index * 90;
}}>
    {
        var items = @getViewport();
        for (var i = 0; i < items.length; i++) {
            var dX = (i + 1) * 90,
                   dY = 0;
            <Item data={items[i]} style={transform: `translate3d(${dX}, ${dY}, 0px, 0px)`} />
        }
    }
</FlipMove>
```

The same thing would likely be applied for transitions as well:
 existingTransition = (index, child) => {
  return 'SOME TRANSITION HERE';
}

For the interim I think doing something like this will make far more sense than attempting to parse the DOM.

**Comment by joshwcomeau** [comment]
So yeah, this would work, but I really don't want to add a new API prop for something that can be done internally. I think it'd be really hard to explain succinctly in the docs, and I wanna avoid the case of having a really complex API. <FlipMove> should be plug-n-play, the user shouldn't have to worry about stuff like this.

That's in my ideal world, at least. In the meantime, I don't feel like it's an urgent enough problem to warrant this kind of fix.

**Comment by joshwcomeau** [comment]
Gonna close this, as it's over a year old. These days I only have bandwidth to tackle critical bug fixes, and maintenance.
