### ISSUE TITLE
Huge mistake in README

### ISSUE THREAD

**Issue by dehghani-mehdi** [joshwcomeau/react-flip-move#219]
Hi,

:D I was joking, it's not huge!

You may remove `style="color: red;"` from following part of README file.

```
// JSX
<FlipMove typeName="ul">
  <li key="a">Hello</li>
  <li key="b">World</li>
</FlipMove>

// HTML
<ul style="color: red;">
  <li key="a">Hello</li>
  <li key="b">World</li>
</ul>
```

Great package, btw.

Thanks!

**Comment by Hypnosphi** [comment]
Hi @dehghani-mehdi ! Mind opening a PR?

**Comment by joshwcomeau** [comment]
Thanks for the heads-up! Not sure how that happened o_O

I happen to be adding a separate PR so I'll do this real quick.
