### ISSUE TITLE
Extra Div

### ISSUE THREAD

**Issue by marcus433** [joshwcomeau/react-flip-move#22]
I recently noticed that after any divs are animated they are encapsulated within another div. To note: It says translate3d rather than translate as I am using my fork.
![screen shot 2016-04-09 at 5 27 52 pm](https://cloud.githubusercontent.com/assets/4731718/14407315/9ad48336-fe78-11e5-8e93-b7d1dd50a6e7.png)

**Comment by joshwcomeau** [comment]
Very strange. I'm trying to replicate that problem now and I'm not able to... is it possible it's relating to the fork?

If not, can you provide more details about how you got that to happen? What props, what do the children look like?

**Comment by marcus433** [comment]
Never mind, my bad, it's something outside of the fork entirely. Sorry for the trouble.

**Comment by joshwcomeau** [comment]
No problem!
