### ISSUE TITLE
duration property affects all animations

### ISSUE THREAD

**Issue by talarari** [joshwcomeau/react-flip-move#228]
i want to enter/leave animations to be slower than the re-ordering animations.
seems like duration affects all animations right now, is it possible to have duration not affect enter/leave animations?

**Comment by joshwcomeau** [comment]
Sorry for the delay in responding! Life has been hectic.

Unfortunately, this isn't something possible right now, and I can't think of any simple workaround. I don't think it would be that easy to solve, either, and don't really see having the time to dig into it.

If this is critical for you, I'd suggest forking the project and trying to solve it yourself; depending on your usecase, you may be able to skirt some of the interrupt issues I'm imagining (if you don't foresee needing to shuffle while an enter/leave is still in progress).

Wish I had better news :( sorry again for the delay
