### ISSUE TITLE
Elements jumping around

### ISSUE THREAD

**Issue by lmenus** [joshwcomeau/react-flip-move#231]
Hello,

I have come across this issue where elements under `<FlipMove>` tend to jump around when elements in array are modified (add, update, delete). See an example below -> yellow button should not jump on the first press, it should behave the same way as on subsequent clicks.

![whatisgoingon](https://user-images.githubusercontent.com/12529395/43135126-42f7f43e-8f3c-11e8-859b-e62031e1be60.gif)

After narrowing it down as much as I can, it appears the issue stems from using `react-i18next`. When I wrap my component like this...

```js
import { translate } from 'react-i18next';
import { connect } from 'react-redux';

// code code code

export default translate()(connect(JumpyComponent));
```

This behaviour can be replicated. However, if I remove translations, like this...

```js
import { connect } from 'react-redux';
import { translate } from 'react-i18next'; // I keep import, just don't wrap the component in it

// code code code

export default connect(JumpyComponent);
```

Everything works as expected.

![morelikethis](https://user-images.githubusercontent.com/12529395/43135422-46790fca-8f3d-11e8-92b9-ba54c901dac0.gif)

Can anyone point me to what might be going on? Here's the `translate()` method from `react-i18next` -> https://github.com/i18next/react-i18next/blob/master/src/translate.js

**Comment by tobilen** [comment]
flip-move uses references and actual dom for position calculation. if some other hoc modifies it -which react-i18next would be able to, see https://github.com/i18next/react-i18next/blob/master/src/translate.js#L60 - it might cause flip-move to incorrectly assume an elements current position.

if i had to debug this, my first steps would involve delaying execution of click behavior to give the ref time to (re)set itself.

**Comment by lmenus** [comment]
Great, thank you @tobilen! Luckily, I was able to work around this without going on the delay journey by importing `t()` in different ways. Still I thought it might be useful to have a thread in case anyone else comes across this in the future. Thanks!
