### ISSUE TITLE
Confused by versioning/changelog/tags etc.

### ISSUE THREAD

**Issue by rhys-vdw** [joshwcomeau/react-flip-move#235]
@joshwcomeau is it possible you've forgotten to push the latest versions? package.json is currently at 3.0.0, but the latest release on npm is 3.0.2. There is a tag for 3.0.1, but no tag for 3.0.2.

There is not GitHub release for 3.0.2 either (presumably because of the lack of tag).

**Comment by joshwcomeau** [comment]
Ack. Sorry about that, not sure how it happened o_O.

I did have the 3.0.2 commit sitting on my computer. I don't see 3.0.1 anywhere :/

I pushed 3.0.2 now, and will add a release as well.

**Comment by joshwcomeau** [comment]
Release added. Closing the issue since I think it's been dealt with, but sorry again for the confusion!
