### ISSUE TITLE
classnames is not found. Also i think the package is not installed correctly for new version on 'npx create-react-app...'

### ISSUE THREAD

**Issue by sameersitre** [joshwcomeau/react-flip-move#236]
./src/Board.js
Module not found: Can't resolve 'classnames' in '/Users/sameersitre/Documents/version-control/2048/2048-react/src'

**Comment by rhys-vdw** [comment]
`src/Board.js` is not from this package, and react-flip-move does not import classnames anywhere. Your issue name talks about create-react-app not react-flip-move.

Closing as invalid.
