### ISSUE TITLE
Wrong position when add item quickly

### ISSUE THREAD

**Issue by zhaoyao91** [joshwcomeau/react-flip-move#244]
I've made a notification system with react-flip-move. It works fine if I add item one by one. But if I add items quickly, the position new item occurs is wrong.

see

![Kapture 2020-02-17 at 18 50 53](https://user-images.githubusercontent.com/3808838/74647349-78c07d00-51b6-11ea-9609-a21fd71c9129.gif)

**Comment by tobilen** [comment]
i suggest you solve this in your codebase by using some method of `debounce`, with the debounce timer being the length of your animation. here are three examples:
* [lodash](https://lodash.com/docs/4.17.15#debounce)
* [rxjs](https://www.learnrxjs.io/learn-rxjs/operators/filtering/debounce)
* [react hooks](https://dev.to/gabe_ragland/debouncing-with-react-hooks-jci)
