### ISSUE TITLE
Enter/leave animations set to false triggers console errors 

### ISSUE THREAD

**Issue by ellerycrane** [joshwcomeau/react-flip-move#25]
When enter/leave animations are set to 'none' or false, I see lots of console errors:

![image](https://cloud.githubusercontent.com/assets/784493/14464765/3eaa5cfc-009e-11e6-985a-9998e58b4b0c.png)

**Comment by joshwcomeau** [comment]
Ack. Looking into this now. Thanks for the heads-up!

**Comment by joshwcomeau** [comment]
Just published v2.0.5, which fixes this issue. Sorry about that!
