### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code.  Please update the following components: FlipMove

### ISSUE THREAD

**Issue by Bishesh58** [joshwcomeau/react-flip-move#256]
![FlipMove](https://user-images.githubusercontent.com/62319684/105631287-a62ba580-5eb2-11eb-8610-01638c20ba91.png)

Anyone having this issue? I had used FlipMove previously but had no issue. I'm using "react": "^17.0.1" & "react-flip-move": "^3.0.4" for this simple project and had this issue. Could anyone help with how to fix this issue?

**Comment by belferink1996** [comment]
Same for me...

**Comment by tobilen** [comment]
this is unlikely to be adressed, seeing as the project is not maintained anymore. and refactoring the existing implementation to functional components would mean a major rewrite.

i suggest you switch to https://github.com/aholachek/react-flip-toolkit or some other alternative.

**Comment by Bishesh58** [comment]
Thank you, Tobilen for the suggestion. I will look into alternatives. Thanks!
