### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by benwaffle** [joshwcomeau/react-flip-move#26]
I'm using Firefox 47.0a2 (developer edition)

**Comment by joshwcomeau** [comment]
Shit. It's because of an inconsistency with `getComputedStyle`.

Found the issue, will hopefully deploy a fix within the hour.

**Comment by joshwcomeau** [comment]
ok! Just published a fix.

Really sorry about that; I neglected to do any browser testing with the final product. Will go through it much more carefully in the coming days to ensure full compatibility, but I tested it with a wide variety of enter/exit animations and can't find any problems :)
