### ISSUE TITLE
If I switch the list quickly, the list data may not be displayed

### ISSUE THREAD

**Issue by taixw2** [joshwcomeau/react-flip-move#260]
![image](https://user-images.githubusercontent.com/12482817/120464718-d1c61b80-c3cf-11eb-8f83-769de51a9f75.png)

Demobox: https://stackblitz.com/edit/react-6p9tng?file=src%2F1_Shuffle.jsx

Please check the image above or run this demo, you can see that the list has data, but it is not rendered.

1. it may be difficult to reappear, but the problem will appear after a few more tries.
2. Maybe the data is: 7 -> 0 -> 7 and it will appear

**Comment by naveenraina** [comment]
I am also facing exact same issue. It was working from last few years but after I made more changes which resulted in changing data quickly, the data disappears half of the times.

**Comment by naveenraina** [comment]
@taixw2 looks like this issue is already answered here -
https://github.com/joshwcomeau/react-flip-move/issues/195#issuecomment-351614576

leaveAnimation={null} worked for me.
