### ISSUE TITLE
Something broken in sizing / position in v2

### ISSUE THREAD

**Issue by neagle** [joshwcomeau/react-flip-move#31]
Hi! First off, thanks for your work on this project: I added v1.4 to a project at work last week and it's been dynamite. It's wonderful to be able to add such attractive animations to React transitions.

Here's an example of the widget I've been working on using v1.4 of `react-flip-move`, working as desired:

![animation-working](https://cloud.githubusercontent.com/assets/176993/14503771/865a1178-017f-11e6-816b-46eb67417d97.gif)

When I tried to upgrade to v2, the positioning / sizing of elements seems to be broken.

![animation-bug](https://cloud.githubusercontent.com/assets/176993/14503952/80d02304-0180-11e6-8030-ea10e2b07449.gif)

I don't mean to make you responsible for solving my problem, exactly, but I wondered if it might ring any bells in terms of changes that happened in the move to v2.

Cheers!

**Comment by joshwcomeau** [comment]
Ack! 

I have a vague idea what's going on; I won't bore you with the details, but when items are exiting, I position them absolutely. I do my best to make them stay in the exact same place, using bounding boxes, computedstyles, and offsetting margin, and it's worked in every case that I've seen until this one!

So, I definitely want to help you fix this, so that the module can handle whatever small detail is screwing it up here.

Is this project open-source? If so, can you point me to the components and stylesheets (if applicable) in question? If not, can you let me know exactly what styles are applied to the items?

Thanks for such a detailed issue!

**Comment by neagle** [comment]
Unfortunately, it's not open source. Let me see if I can recreate the module in a standalone way tomorrow. Thanks for your willingness to help!

--
Nate Eagle

**Comment by benwalks** [comment]
Hi @joshwcomeau, I'm having what I think might be a similar issue.

![react-anim](https://cloud.githubusercontent.com/assets/8383204/14512371/e2cd0a30-0221-11e6-82f8-598af62c281d.gif)

The styling for each of those 'answers' is:

`.collab-answer-wrapper {
      background-color: #FFF;
      border-radius: 20px;
      padding: 1em 2em;
      margin-bottom: 1em;
      .collab-answer {
        font-size: 16px;
      }
      .collab-author {
        margin-bottom: 0px;
        font-weight: 700;
        color: #7C49B8;
      }
    }`

Thanks!

**Comment by joshwcomeau** [comment]
Hey @benwalks,

There's definitely something weird going on here. The items should be shifting up out of the way, when a new item is introduced. And, from what I can see, it looks like the exit animation isn't positioning itself properly, similar to Neagle's issue. Can you please share:

* The styles on the parent? It seems like you're vertically centering all the items (both the FlipMove and the stuff above/below it), and I'm wondering if that's mucking it up somehow.

* The JSX for the component? Just curious how the children are being dynamically generated, maybe I'll see a clue

Will do my best to get a fix shipped for this quickly :)

**Comment by benwalks** [comment]
Great, thanks Josh.  I was justing looking, perhaps it's flexbox related?

This is the component more or less:

```
export default CollabResults = React.createClass({
  propTypes: {
    answers: React.PropTypes.array.isRequired
  },
  renderAnswers() {
    if (!!this.props.answers) {
      return this.props.answers.map((answer, index) => {
        return <CollabResult key={answer._id} id={answer._id} userId={answer.userId} author={answer.author} content={answer.content} />;
      });
    } else {
      return <div className="text-center"><p>What will your rule be?</p></div>
    }
  },
  render() {
    return (
      <FlipMove enterAnimation="elevator" leaveAnimation="elevator">
        { this.renderAnswers() }
      </FlipMove>
    )
  }
});
```

This is the SCSS for that whole section.

```
.collab-section {
    background: #E95794;
    background: -moz-linear-gradient(top, #E95794 0%, #EBCDDA 100%);
    background: -webkit-linear-gradient(top, #E95794 0%,#EBCDDA 100%);
    background: linear-gradient(to bottom, #E95794 0%,#EBCDDA 100%);
    background-size: cover;
    display: flex;
    align-items: center;
    padding-top: 6em;
    padding-bottom: 6em;
    span.glyphicon.glyphicon-remove {
      font-size: 10px;
    }
    .collab-wrapper {
      margin-top: 2em;
    }
    .question-logo {
      position: relative;
    }
    .collab-answer-wrapper {
      background-color: #FFF;
      border-radius: 20px;
      padding: 1em 2em;
      margin-bottom: 1em;
      .collab-answer {
        font-size: 16px;
      }
      .collab-author {
        margin-bottom: 0px;
        font-weight: 700;
        color: #7C49B8;
      }
    }
    .question-button {
      margin-top: 2em;
    }
  }
```

**Comment by joshwcomeau** [comment]
hey @benwalks!

Alright, so I've been able to successfully re-create the bug, and I understand the issue, but it's a tough one.

Essentially, in order for the animation to work, I need to take items that are being removed out of the document flow, so that the siblings can treat it as though it doesn't exist, and slide into its location as it fades away.

I position it absolutely, and try to figure out exactly where it needs to be based on its distance from the top left corner of its parent container.

This works when items are top-aligned, because the fading element's location (relative to its parent) won't change as it's fading away. In your case, though, items are center-aligned. The actual animation looks 100% fine to me, the problem is that it "jumps" down immediately by half a position. If you notice, the animation starts from exactly where its sibling ends, after the transition.

It's getting kinda late and my brain's shutting down for the day. Will keep poking at it tomorrow; I have a couple ideas, but I'm concerned those ideas will break it in more common scenarios D:

**Comment by joshwcomeau** [comment]
@neagle let me know if you can re-create your issue; I think it may be unrelated, and hopefully easier to fix!

**Comment by benwalks** [comment]
No worries @joshwcomeau, thanks for being awesome.

**Comment by joshwcomeau** [comment]
Happy day @benwalks! I found a solution!

The solution, as it stands right now, causes another edge case to fail (if you supply a custom enter/leave preset that has a `transform: translate` property). Work being done by @marcus433 should allow me to fix this edge case and pen a proper release :)

In the meantime, if you want to use the fix, it is published to NPM under `2.1.1-beta1`. If you use that version, exit animations should be solved :)

(sidenote: enter animations aren't 100% ideal yet either; even in your gif, the items don't slide up gradually, they JUMP up when you add the new item. That's another bug for another day, but something I intend to tackle)

So yeah, please let me know if this new version works properly!

**Comment by benwalks** [comment]
Awesome Josh, thank you. Ill let you know how it works tomorrow!

**Comment by benwalks** [comment]
Hey Josh, just tested and am getting the following error.  Any thoughts?

```
TypeError: Cannot read property 'getBoundingClientRect' of null
    at http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:61824:31
    at Array.reduce (native)
    at FlipMove.componentWillReceiveProps (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:61817:50)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:6989:14)
    at wrapper [as updateComponent] (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:896:21)
    at ReactCompositeComponentMixin.receiveComponent (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:6936:10)
    at Object.ReactReconciler.receiveComponent (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:5217:22)
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:7093:23)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:7075:10)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:3000/packages/modules.js?hash=26776b4ca95bdb1aa45f097ea49d098ab78a9c01:7004:12)
```

**Comment by joshwcomeau** [comment]
Hm, very weird! Typically that means that the DOM node we're trying to relocate has already been removed from the DOM. I'll have a look and see if I can spot the problem.

**Comment by joshwcomeau** [comment]
Hey @benwalks! I'm gonna create a new issue, since this issue is unrelated to the original one, and it's getting a little too cluttered for me. Will post my latest findings there and CC you :)
