### ISSUE TITLE
Awesome use of React Stories

### ISSUE THREAD

**Issue by arunoda** [joshwcomeau/react-flip-move#32]
Hey, 

I'm one of the creator of React Storybook, I just saw you've used Storybook with your app. That's a pretty cool use of it.

We experimented with a way to deploy Storybook to GH pages and it works. 

* [Demo](http://kadira-samples.github.io/react-button/)
* [Code](https://github.com/kadirahq/react-cdk/blob/master/generators/app/templates/.scripts/publish_storybook.sh)

We'll make it generalized soon.

We are also planning to add new notes tab next to the Action log. So, you may can write some notes may be kind of documentation like this:

```js
var stories = storiesOf('FlipMove', module);

stories.add(
  'simple transition', 
  () => (
    <Controls duration={400} />
  ), 
  `
    This is the basic transition and you can simply use it like this:

    ~~~js
    <Controls duration={400} />
    ~~~
  `
);
```

I can send you a PR once we are ready. Would like for that?

**Comment by joshwcomeau** [comment]
Hi Arunoda!

First, thanks so much for your work on React Storybook, Mantra, and Flow Router. I always enjoy Kadira releases =)

GH pages deploy is huge; At work we're moving to React and we'd like to use Storybook not only for dev but as a library of components for the Product team to browse and review. We were going to start investigating a way of deploying it, so I'm glad to hear that work is underway.

I would love a PR; notes seem like a great feature to have! As the size of the list of the stories grows, having something on the page showing me the exact config of each story would be helpful.

Thanks.

**Comment by arunoda** [comment]
Awesome. Will update you with a PR.

**Comment by joshwcomeau** [comment]
Thanks @arunoda! Going to close this now but will accept a PR at your convenience :)
