### ISSUE TITLE
Document & apply the "typeName" property in the examples

### ISSUE THREAD

**Issue by ConneXNL** [joshwcomeau/react-flip-move#33]
According to https://www.w3.org/TR/html-markup/ul.html you are only allowed to wrap a `<li>` elements in an `<ul>`. Yet the examples of React-flip-move wrap a div inside the ul.

I was looking for a solution in my project when i found the "typeName" property in the code but this is not documented. I also suggest to make the examples use this "typeName" to prevent the 
`<ul><div><li></li></div></ul>`.

**Comment by joshwcomeau** [comment]
Hey,

Ack! Can't believe I forgot to document `typeName`. I also forgot `className` and `style`.

You're absolutely right about the examples not corresponding to the HTML spec. Went ahead and used the `typeName` property to ensure there's no intermediate div between the list and list items.

Thanks for pointing it out :)
