### ISSUE TITLE
Wrong animation with nested transition

### ISSUE THREAD

**Issue by havenchyk** [joshwcomeau/react-flip-move#37]
Hi, first of all thanks for your amazing work!

I came across the problem, when the child element has transition, in this case all the animations, including first level child ( list item for which i would like to enable animation). Hope it's clear :)

**Comment by havenchyk** [comment]
I guess this https://github.com/joshwcomeau/react-flip-move/issues/29 relates

**Comment by joshwcomeau** [comment]
Hi,

Thanks for the kind words!

I'm not sure I understand the problem... I understand that there's something wrong with nested FlipMoves, where the children are being affected by the parent. Is it enter/exit animations? General transition settings like `duration`?

If you can provide a snippet (or, better yet, a codepen) that showcases the problematic situation I would greatly appreciate it :)

**Comment by havenchyk** [comment]
Actually, I'll try to reproduxe with codepen, but the reason of issue is somewhere in the scheme:
- FlipMove
    - item
    - item
    - item


And inside the item I have e.g. button with "transition: .1s background-color", that breaks the animation of moving the item.

**Comment by havenchyk** [comment]
So to disable this behavior I need to add workaround like
- add class to override transition to none on startAnimation
- remove this class and on afterAnimation

It's the only solution I see, but in docs you said that fleepMove will override the transitions.

**Comment by joshwcomeau** [comment]
Hmm, I can't reproduce this. For me, items _inside_ the FlipMove items work just fine.

I tried to recreate the situation you described:
```
<FlipMove>
  <li key="itemA">
    <button style={{ transition: '100ms background' }}> // This should not override it, it's on a different element
      Button Text
    </button>
  </li>
  <li key="itemB"> .... </li>
  <li key="itemC"> .... </li>
</FlipMove>
```

And it works perfectly.

If you can please create a codepen that showcases the problem, it would help me understand :)

**Comment by havenchyk** [comment]
Yeah, it's my case, I'll try to reproduce on codepen tiday, thanks!

**Comment by havenchyk** [comment]
Probably I've got it. http://codepen.io/VladimirHavenchyk/pen/VaBdOM?editors=0010 @joshwcomeau please, click on button 1 and don't move your mouse, just click again and again, I guess, you will see the problem. It's not the original issue, but I faced it as well.

**Comment by joshwcomeau** [comment]
Ah-ha!

Thanks so much for taking the time to put the pen together :)

I definitely see the issue; the hover effect is affecting the button's ability to transition smoothly. Will try to fix in the next day or two.

Weird that it isn't the original issue, but I'll tackle this one and hopefully it'll fix both!

**Comment by joshwcomeau** [comment]
I found the problem!

The issue was I had registered an `onTransitionEnd` handler to do some necessary cleanup after the FlipMove transition had completed. Because events propagate, the hover effect's transition was triggering this cleanup prematurely, which was causing the item to "jump" to its new position.

v2.1.2 fixes this issue :) Please reopen if there are any other issues!
