### ISSUE TITLE
OnFinishAll doesn't fire when when disableAllAnimations=true

### ISSUE THREAD

**Issue by vermiliongrey** [joshwcomeau/react-flip-move#39]
I imagine this shares the same root cause as #38, but I thought I'd file a separate report just in case.

**Comment by DiogoDoreto** [comment]
Maybe this is an expected behavior. The way I see it is like this: if animations are disabled then they are not starting therefore not ending as well. To me it makes sense not triggering callbacks.

**Comment by joshwcomeau** [comment]
It is indeed intended behaviour! `onFinish` callbacks only fire at the end of transitions. if there's no transition, there's no need to fire a callback.

If animations are always disabled, it is easy enough to just fire the method whenever the props change. if the animations are variable, it's a bit trickier... 

What's your use-case? Maybe there's a reason to enable them that I haven't thought of

**Comment by vermiliongrey** [comment]
Ah, I see. That makes sense.

I was originally trying to find a work around for #38 by setting isDisableAnimation to false after render. But I guess once #38 is fixed, it won't be an issue for my use case.

**Comment by joshwcomeau** [comment]
Hi @vermiliongrey!

Just released v2.1.3, which fixes the `disableAllAnimations` bug :) 

For me, there's always a tricky balance between 100% support for every desired feature, and keeping the API small and manageable. There's already something like 14 different settings that can be tweaked with props, and so I'm trying to be super selective with new additions.

I'll keep an ear open and if I see this feature request come up more often, I'll definitely reconsider :)

Let me know how it goes with the bugfix!
