### ISSUE TITLE
Request: add onStartAll callback

### ISSUE THREAD

**Issue by DiogoDoreto** [joshwcomeau/react-flip-move#41]
... to pair with onFinishAll :)

Example use case: having an `animating` class on the parent node only when the animation is happening.

**Comment by joshwcomeau** [comment]
Yeah, hmm. My initial reasoning for not having this is that it's really simple to fire arbitrary events at the _start_, you can just add a callback to `componentDidReceiveProps`. 

But, it's much less simple to be able to trigger things on the children, and the onFinish callbacks do provide references to the element.

Will investigate this!

**Comment by DiogoDoreto** [comment]
The thing is that animations may or may not happen when data changes. Having the callback inside the library would guarantee that if you have the start event then you know that you will have an end event as well.

**Comment by joshwcomeau** [comment]
Done :) v2.2.0 has a symmetrical `onStartAll` callback!

I actually forgot that I had added an `onStart` callback, which is why I was hesitant to add this one. Once I remembered that I had already been convinced to add an `onStart`, adding `onStartAll` just made sense
