### ISSUE TITLE
Remove dist/ files from main branch, serve via CDN

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/react-flip-move#42]
I'm really sick of having to check in the built and minified js files. They clutter up diffs, and I often forget to build before committing. 

The solution is to use something like [jsDelivr](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md) to serve those files.

Will spend some time soon getting this done.

**Comment by davidkpiano** [comment]
Can you add it to the `.gitignore` but not the `.npmignore`? And just have them build with a `prepublish` script.

**Comment by joshwcomeau** [comment]
@davidkpiano indeed, but I want to have it be available as a link, so people can use a script tag in a fiddle and play around with it.

Blew my mind when I discovered you can publish stuff to NPM that is not committed to github, already using the trick for the `lib` files :)

**Comment by davidkpiano** [comment]
> I want to have it be available as a link, so people can use a script tag in a fiddle and play around with it.

www.npmcdn.com 😉

**Comment by joshwcomeau** [comment]
:0

Thank you!

**Comment by joshwcomeau** [comment]
`4 files changed, 4 insertions(+), 951 deletions(-)`

Lovely. Really appreciate it :)
