### ISSUE TITLE
Allow for graceful interrupts

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/react-flip-move#45]
Right now, if an animation is interrupted, the results can be jerky. By considering the current translation at the start of the transition, we should be able to transition from that origin to the destination.

**Comment by vermiliongrey** [comment]
this would be really useful, I tried using FlipMove in junction with a live list filter and it didn't work because of the interruptions.

**Comment by joshwcomeau** [comment]
Hey @whitegrey,

I believe I've solved this problem :) It works perfectly for me, but I would like to have you and a couple other people test it in real projects before I accept the PR.

Can you please NPM install `react-flip-move@beta` and give it a go?

Thanks =D
-Josh

**Comment by whitegrey** [comment]
Hey Josh,  thanks for the hard work!

It's not operating as I had hoped, although it's possible we may have been talking about different things. I took a short video of what it looks like on my end:

https://vid.me/1qP2

I've included the implementation details in case it's of interest:

```
var collectionList = collectionObj.map(function(currentItem, index, array){
	var stringifiedItem;
	//Create a string of all the Collection item property
	for(var currentIndex in currentItem)
		stringifiedItem += JSON.stringify(currentItem[currentIndex]).toLowerCase();

	//Search for match
	if (stringifiedItem.indexOf(searchText) > -1)
		return currentItem;
})

//Remove all the undefined elements from the map array
var collection = _.pull(collectionList, undefined);

return collection;
```

```
var collectionDOM = collection.map((currentItem, index, array)=>{
	if (currentItem.ID == 'seperator')
 	 	return <Seperator />;
	else
		return <Item />;
});
```


```
<FlipMove > 
	{collection.length > 0 ? collectionDOM : <NoItems />}
</FlipMove>
```

**Comment by joshwcomeau** [comment]
Ahhh, right; this is separate from what I fixed. I was specifically tackling re-order interrupts.

I have a short-term solution for you, and that's to debounce the typeahead by at least the length of the transition duration. So if you have a 300ms transition, only update the props at >=300ms intervals. This should fix the issue, and also be nicer to your server :)

But yeah, I will try and fix this soon as well. I think I have an idea of what's going on. Thanks for testing it, and for providing so much info!

**Comment by joshwcomeau** [comment]
@whitegrey, I think I've more-or-less fixed it :) Can you please install and test `2.4.0-rc2`?

There are still some subtle issues when items are entered/exited in rapid succession, but I tried a similar use-case to yours and it works for me. It's miles above the glitchy retriggering in 2.3, but I wanna make sure there aren't some unintended consequences before I release it.

Thanks!

**Comment by valentinvichnal** [comment]
Hey Josh,

I had a similar issue, in a Feed component I get the data from a Meteor collection.
Adding/removing documents too rapidly in the collection caused a bug, the old documents remained in the component and the new documents overlapped them.

I thought it was my fault but `rc2` solved this!
Thank you for keep maintaining your awesome library! :+1: 

Quick question about key prop, do you think there are benefits to use custom id as a key prop, or map's index is enough?

**Comment by joshwcomeau** [comment]
@valentinvichnal thanks for the kind words! Happy to hear that rc2 solved your issue, but a word of warning: there's a bug in that version that causes `onFinishAll` to not be called when items enter/exit frequently. It may have more serious consequences as well (memory buildup?). Still trying to understand/fix it.

So you actually can't use the map index if you want items to shuffle :) consider the following:

```js
['a', 'b', 'c'].map( (val, index) => {
  console.log(val, index); // 'a', 0
}
```

Then, when the order changes:

```js
['b', 'c', 'a'].map( (val, index) => {
  console.log(val, index); // 'b', 0
}
```

FlipMove will think that nothing has changed, because index 0 is still in position 0. If you used the `val` as the key, FlipMove would see that the items had changed positions.

**Comment by valentinvichnal** [comment]
Okay, cool thanks!
I've always used the documents' id from db as keys, and I was thinking to use map index where I don't need this id for other use, but your explanation makes sense. :)

**Comment by whitegrey** [comment]
Hey Josh, sorry for the late reply, 

RC2 definitely makes thing a lot better. There's still some stuttering when modifications are made too quickly: https://sendvid.com/2pj4rv0u

But it's definitely usable. I've added it to the live version of my project if you'd like to take a look at the implementation in action in case it help you: http://senpai.co

**Comment by joshwcomeau** [comment]
hey @whitegrey,

That's a really cool project! Would you mind if I tweeted it? Flip Move gets downloaded quite a bit but I haven't seen many real-world implementations :)

As for the stuttering, I haven't had the chance to keep working on RC2. Will hopefully find some time in the next couple weeks.

**Comment by whitegrey** [comment]
Hah, thanks! Of course I don't mind, though to be honest, the project is still in beta and in a pretty rough state.

**Comment by whitegrey** [comment]
It seems that 2.4.0 proper seems to have broken part of the fixes introduced in rc2.

Here's a video:
https://vid.me/Y1UP

in comparison to rc2:
https://vid.me/aLzZ

**Comment by valentinvichnal** [comment]
Yes unfortunately 2.4.0 broken again.

**Comment by valentinvichnal** [comment]
Yes unfortunately 2.4.0 broken again in my project too.

**Comment by joshwcomeau** [comment]
yeah, sorry guys; 2.4 wound up being an unrelated patch. 2.4 rc2 will still work if you set an explicit dependency.

Haven't found the time to resolve the perf issues with that patch, so I don't feel comfortable releasing it when it (IMO) introduces more problems than it solves.

**Comment by SDSLeon** [comment]
2.4 rc2 graceful interrupts not work in safari =( and I see bug with not disappearing items: animation end but items still in the dom with animation classes and new one item there too. Also will be cool to separate the staggerDurationBy and staggerDelayBy on enter/leave and reorder.

**Comment by joshwcomeau** [comment]
Yeah, it's pretty buggy. Didn't know it was broken in Safari.

Graceful interrupts are tricky, and I think I might go with a different approach. Insightful and/or brave contributors welcome!

**Comment by joshwcomeau** [comment]
So this isn't _totally_ solved, firefox is still jerky, but it's solved enough for me, for now :)
