### ISSUE TITLE
Look into spring-based motion

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/react-flip-move#47]
I really like [React Motion](https://github.com/chenglou/react-motion). While I wouldn't want to include it as a dependency for this project, it may be possible to create an optional, spring-based transition.

Worth looking into!

**Comment by marcus433** [comment]
http://dynamicsjs.com/ may be a good option. It's quite lightweight and its interface would work well with the flip-move setup.

**Comment by joshwcomeau** [comment]
Awesome, that does look good.

**Comment by joshwcomeau** [comment]
Doing some cleanup. I don't foresee having the time to work on this, and nobody else has nabbed it. Feel free to reopen if someone wants to look into it :)
