### ISSUE TITLE
No more dist folder?

### ISSUE THREAD

**Issue by jamby** [joshwcomeau/react-flip-move#51]
Was wondering where the folder is for the distributed files are.

**Comment by joshwcomeau** [comment]
I removed 'em from the repo.

The /dist (concatenated) and /lib (transpiled) files are still available via NPM, when you install it. 

The other use-case, using a script tag when playing around in a jsbin, is now covered by CDN:

https://npmcdn.com/react-flip-move@2.1.4/dist/react-flip-move.js
https://npmcdn.com/react-flip-move@2.1.4/dist/react-flip-move.min.js

Let me know if there's a third use-case I'm not aware of!

**Comment by jamby** [comment]
Messaged you on Reddit about this, but since I'm using it in a Rails project, I am trying to use it via rails-assets. Which uses bower.

I add this repo on rails-assets and it adds your project via a game called `gem 'rails-assets-joshwcomeau--react-flip-move`. That makes it so I have to do a require file inside another js file for me to use them (not sure if you're familiar with Rails asset pipeline).

Currently, there is no way to get the latest version because there is no dist file, and if I try `//= require react-flip-move/src/FlipMove.js` it does not work at all.

**Comment by jamby** [comment]
Also, not my choice to be still using it this way. I tried to get npm and package.json working for the project, but was denied by higher ups. I also tried "vendoring" the minified file, but then it got yelled at in code review because I should be using a gem.

Can never win.

**Comment by joshwcomeau** [comment]
Blah. Sorry to hear that!

I am indeed familiar with Rails' asset pipeline, although it's been a while; I remember hating it, and it shocked me recently when I found out that Bower is still the package manager of choice. 

I'm really happy to have gotten the /dist files out of the repo; they bloated git diffs, and were a hurdle for new committers. I'm not really willing to re-include them for a bureaucratic edge case. Sorry =(

I see two options for you:

* Stick to using 2.1.2. Future versions of this will have a few little niceties, but if it works for your purposes, there's no huge reason to need the latest versions (unless you plan on keeping up-to-date with React, in which case there's a chance it will break when React has breaking changes).

* Create a Bower package that includes the /dist. I have no problems with you owning the Bower release, I'll even link to it in the README :) I'd do it myself but I don't want the burden of maintaining it.

Let me know if either of these solutions are acceptable :)
