### ISSUE TITLE
item.entering = true; blows up

### ISSUE THREAD

**Issue by jsg2021** [joshwcomeau/react-flip-move#63]
[This line](https://github.com/joshwcomeau/react-flip-move/blob/13a34664e322faed6691fbda988e7b0c25d47c2e/src/FlipMove.js#L461) is blowing up in React 15.2.1 (item is sealed)

**Comment by joshwcomeau** [comment]
Ahh, yeah, makes sense. I should be cloning the state items, not modifying them directly.

Will fix shortly!

**Comment by joshwcomeau** [comment]
So, weirdly I was unable to get any sort of warning or error with React 15.2.1.

I definitely shouldn't've been mutating state, though, so I just published [v2.4.1](https://github.com/joshwcomeau/react-flip-move/releases/tag/v2.4.1), which instead creates a new object from the state item.

@jsg2021 please let me know if this version fixes the issue :)

**Comment by joshwcomeau** [comment]
Going to close this, because I believe it to be fixed :) feel free to disagree!

**Comment by jsg2021** [comment]
Sorry for the delay. When I observed it, I was on React 15.2.1 dev code. (the un-minified) 

I updated my node modules yesterday and didn't see the error. :)
