### ISSUE TITLE
Handling key changes

### ISSUE THREAD

**Issue by gregj1** [joshwcomeau/react-flip-move#67]
Fantastic library - just works.

I'm using it to animate lists of items, populated by a redux store and backed by a server-side API. When a user creates a new item I "optimistically" put it into the brower's redux store and assign it a temporary ID. After the server interaction completes I go back and renumber the item with the server generated ID. I think this is a reasonably common practice.

react-flip-move interprets the renumber as a "delete/add" operation and plays two animations very quickly.

I wonder how other developers are dealing with this situation?

One option I've considered is keeping a mapping in the component's state and remapping from server-generated-id to temporary-id in a selector until the component is unmounted.

**Comment by joshwcomeau** [comment]
Thanks for the kind words!

FlipMove uses the `key` prop to determine what's what; as long as your optimistically-rendered list item and the validated "real" item share the same `key`, FlipMove shouldn't mess about with it.

So, I think the solution is to not use the server-generated ID (or its mocked version) as the `key`, but instead to use something you know won't change; the article's title, maybe? Worst case you can generate a specific ID just for the key, and use that for both optimistic and validated versions.

Let me know if that doesn't work for some reason, we'll figure it out :)

**Comment by gregj1** [comment]
Thanks for the reply.

I ended up keeping the temporary ID on my model and continued to use that as the key for flip-move lists even after the server-generated ID was populated.

The _TL;DR_ version for anyone coming along afterwards:

**Don't change keys!** Use a field that won't change. Arrange to keep using locally generated IDs for flip-move even though the ID from your server API may differ.

**Comment by joshwcomeau** [comment]
Awesome, glad to hear it. Added a blurb in the "gotchas" section of the README to address this concern :)
