### ISSUE TITLE
sorting animation

### ISSUE THREAD

**Issue by byjoh** [joshwcomeau/react-flip-move#68]
Is it possible to turn off the sorting animation (and only use onEnter and onLeave)?  I am using React DnD for a sortable list and would like to use FlipMove animations only for items that are deleted, but when I grab and drag an item to re-order the list there is a strange interaction.  For example, if I grab item 1 and drag it above item 2, an infinite loop of 1 swapping with 2 and 2 swapping with 1 occurs until I release item 1.

For more background, in the "hover" callback React DnD is sending the two indices to Redux, which updates the list state with the new order that then is injected back in to my list container via props.

**Comment by joshwcomeau** [comment]
Sorry for the delay! Thought I already replied to this.

The sorting animation is the main feature of Flip Move :) If all you need are leave animations, I would recommend [React CSS Transition Group](https://facebook.github.io/react/docs/animation.html).

The only thing it doesn't have, compared to FlipMove, is the animation presets. You can view those presets [here](https://github.com/joshwcomeau/react-flip-move/blob/master/src/enter-leave-presets.js). You'd just need to update them from keyframe-style animations to the style of React CSS Transition Group.

For example, the `elevator` leave preset is:

```js
{
  'elevator': {
    from: { transform: 'scale(1)', opacity: 1 },
    to:   { transform: 'scale(0)', opacity: 0 }
  },
}
```

You would use it like so, in your CSS:

```css
.your-component-leave {
  transform: scale(1);
  opacity: 1;
}

.your-component-leave.your-component-leave-active {
  transform: scale(0);
  opacity: 0;
}
```

**Comment by RickiWeb** [comment]
Bonjour, I just started using the meteor framework (I'm using version 1.6)
I have a problem with react-flip-move, I get a error ine the client side which is in the attached screenshot just when i import this component " **import FlipMove from 'react-flip-move'** ". 
Ps : I add this module with this cmd: "meteor npm install react-flip-move@2.7.2 --save" 
Maybe the error is stupid but I got stuck, help me please!
thank you in advance.
![react-flip-move error](https://user-images.githubusercontent.com/25333016/33598512-5c8157fa-d9a3-11e7-88e7-bb39644070d8.PNG)
