### ISSUE TITLE
"Hero" animation

### ISSUE THREAD

**Issue by techniq** [joshwcomeau/react-flip-move#69]
Is it possible to perform a "hero" animation (as Polymer calls them) using react-flip-move?

For example, is it possible to replicate [this demo](https://youtu.be/z5e7kWSHWTg?t=9m52s) Ryan Florence showed using Magic Move, or [either](http://morethanreal.github.io/neon-animation-demo/bower_components/neon-animation/demo/tiles/index.html) of [these](http://morethanreal.github.io/neon-animation-demo/bower_components/neon-animation/demo/grid/index.html) Polymer demos, or the transition when selecting an item on [css-triggers](https://csstriggers.com/)?

if so, could you add an [example](http://joshwcomeau.github.io/react-flip-move/examples/#/) or a codepen?

Thanks in advance (and especially for the awesome library, I'm already using it for other use cases)

**Comment by techniq** [comment]
I was able to make some progress (through trial and error) reproducing Ryan's Magic Move demo tonight - http://codepen.io/techniq/pen/qNrYYb?editors=0010

**Comment by joshwcomeau** [comment]
@techniq - Awesome!

I would probably do things slightly differently; rather than have a `selected` value in state, I would just rearrange the items so that the "selected" item is the first in the `items` array. 

```js
  selectItem(key) {
    // Find the selected item in the array
    const head = this.state.items.find(item => item.key === key)

    // get all the items EXCEPT the selected item
    const tail = this.state.items.filter(item => item.key !== key)

    this.setState({
      items: [
        head,
        ...tail
      ],
    })
  }
```

For the actual positioning, I'd use a `:first-child` pseudoselector so that the first item in the list has the styles you've applied with the `.selected` class.

That said, I don't know if this method is actually better than yours, it's just more idiomatic to typical FlipMove usecases. It stays true to the idea that this is just a list of items, and we're animating the "rearranging" of those items.

Thanks for sharing the codepen, I'm sure it'll be valuable to others who see this issue looking to create a similar effect :)

**Comment by techniq** [comment]
@joshwcomeau thanks for the feedback.

I plan to continue exploring more examples I mentioned above (Polymer's neon-animation examples, css-triggers's list item effect, etc).  If you have any insight on how to accomplish those, I'd appreciate it.

**Comment by joshwcomeau** [comment]
@techniq I think those demos may be stretching Flip Move a little too far. It can handle moving the items around, but it doesn't tackle resizing them, and both the demos you mention have an element of growing as they move.

Honestly, if I were to try and accomplish that task, I would probably do it from scratch; could make for a really interesting library, to focus a selected item. I'm imagining an API like:

```js
<HeroMove
  wipeEffect="circle"
>
  <Trigger on="click" finalStyle={{ /* CSS for end position */ }}>
    <Box />
  </Trigger>
</HeroMove>
```

I realize that's not terribly helpful in terms of quick solutions, but if you're looking for a really fun side project, I think it'd be worthwhile :)

**Comment by techniq** [comment]
@joshwcomeau Thanks, good to know.  TBA I'm just now getting into animation with React and feeling things out (trying to understand the pro/cons and limits between react-flip-move, react-motion, and ReactTransitionGroup/ReactCSSTransitionGroup).

So far I've only used your react-flip-move to collapse elements as their are shown/hidden based on input selections, and for a "page transition" as a user moves through different sections of our survey.  I initially tried using react-motion for the collapsing elements, but it appears to be [difficult](https://github.com/chenglou/react-motion/issues/62) without an additional [library/component](https://github.com/nkbt/react-collapse), since the elements had an unknown fixed height to begin with, but react-flip-move (with it's use of `getBoundingClientRect()` worked great.

I'm currently seeing how far I can get with react-flip-move by trying to replicate other animations  I've seen, and when I hit a wall, start looking deeper into motion/transition groups.

Once again, thanks for your quick replies.

**Comment by techniq** [comment]
I wasn't sure if this was worth opening a new issue for, but I was trying to accomplish something related to the original Ryan Florence demo with a slight twist.

I would like to be able to maintain 2 divs of items ("selected" and "remaining"), but have items animate between to the 2 divs (similar to what I showed you yesterday).  Knowing the items are entering/leaving the collections, it seems a single `<FlipMove>` wrapper would be needed, but for it to "peer" deeper than just it's own children (grandchildren/etc).

I created a descent affect using the enter/leave animations with 3 `<FlipMove>` wrappers (http://codepen.io/techniq/pen/WxaxaR), but I was basically hoping to accomplish the original effect 9http://codepen.io/techniq/pen/qNrYYb) but with the ability to select more than 1 item (currently the original affect is using `position: fixed` and would be difficult to support positioning multiple items, especially if they need to wrap.

Thoughts?

**Comment by joshwcomeau** [comment]
Yeah, I can't think of a super simple way to do that. 

A lot of really out-of-the-box ideas like this would need FlipMove to recursively check child nodes, and I decided against that for performance/simplicity reasons. I tried to make this library do one thing and do it well, and adding that complexity would've sacrificed overall stability for a pretty niche use-case.

If this is an important task for you, I'd consider forking FlipMove and add in the ability to compare N-levels deep. Shouldn't be _too_ hard, should just need a function that calls `.childNodes` and iterates through them all, looking for keys.

Let me know if you have any questions about the source. I explained the underlying mechanisms [here](https://medium.com/developers-writing/animating-the-unanimatable-1346a5aab3cd#.hi06agkmb), but beyond that you'll need to do some digging into the code to see how it works.

**Comment by techniq** [comment]
@joshwcomeau Thanks.

Another use case I was considering experimenting with is using FlipMove with react-router for the "hero animations" between routes, but I think it would need this deeper checking to perform the animations.  For example, if I'm showing a list of items with an icon/image and click one, the icon/image would move into position on the details page.  One example of this is clicking on a photo on photos.google.com.

If I get some more time to experiment and make any progress with it, I'll let you know (I wouldn't expect anything too soon though)

**Comment by RomuxX** [comment]
Hi @joshwcomeau ,
The pen http://codepen.io/techniq/pen/qNrYYb?editors=0010 in this comment 
https://github.com/joshwcomeau/react-flip-move/issues/69#issuecomment-237136664 work fine with version 2.14 but not with the latest version.
Can you help me ?

Thanks !
