### ISSUE TITLE
react-flip-move together with react-youtube: enter animation not working correctly

### ISSUE THREAD

**Issue by burggraben** [joshwcomeau/react-flip-move#79]
Hello!
Great work, thank you very much for your projekt.
I experience the following behaviour:

# Context
I am using `react-flip-move` together with [react-youtbe](https://github.com/troybetz/react-youtube). The `react-youtube` component is part of the children array of the `react-flip-move` component. The `react-youtube` component enters and leaves this array, and this should be animated.

When the `react-youtube` component enters the list, two animations should be visible:

1. The `react-youtube` component should be animated (here a fade in)
2. The components that are displayed beneath the `react-youtube` component should move downwards the make place for the new component. 

Exactly as displayed [on the project page](https://camo.githubusercontent.com/0704916f37cac4305f13ea101ed8c34498205b77/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f676974687562646f63732f666d2d666164652e676966).

# Problem
The second animation is not executed when the `react-youtube` component enters the list. So the components beneath the fading-in `react-youtube` component just "jump" to their new places. However the reverse animation, when the `react-youtube` component leaves, is executed correctly

# Code Outline

    import YouTube from "react-youtube";
    import FlipMove from "react-flip-move";

    class extends React.Component {
        constructor(props) {
            super(props);

            this.state = {
                showYouTube: false
            };
        }

        render() {
            const youTubeComponent = (
                <YouTube
                    opts={{width: "100%"}}
                    videoId="someId"
                    key="someYouTubeComponentKey"
                />
            );

            const someDiv = (
                <div key="someDivKey">...</div>
            );
              
            return (
                <div>
                    <StateChangeComponent
                        changeStateCallback={(bool) => this.setState({showYouTube: bool})}
                    />
                    <FlipMove
                        easing="ease-in-out"
                        duration="700"
                        enterAnimation="fade"
                        leaveAnimation="fade"
                    >
                        {
                            (this.state.showYouTube === true ) ? (
                                [youTubeComponent, someDiv]
                            ) : [someDiv]
                        }
                    </FlipMove>
                </div>
            );
        }
    }

Thank you for reading!

**Comment by joshwcomeau** [comment]
Hi Dominik,

So, I took a quick gander at the react-youtube source, and I think I know what the issue is.

react-youtube renders its contents inside a `<span>`. FlipMove has trouble with items that are `display: inline;`, for reasons I haven't spent the time to fully understand.

The solution would be to style that `<span>` to add `display: block` or `display: inline-block`. If you use traditional CSS (or a CSS preprocessor), this is easy. Simply wrap the youtube component in a container and select it with `.your-container > span`.

If you use exclusively inline styles, I'm afraid I don't know an easy way to fix this problem. You should open a PR with react-youtube, and ask them to provide a `containerStyles` prop so that you can apply styles to the wrapping `<span>`.

Let me know if this helps!

**Comment by burggraben** [comment]
Hi Joshua,

many thanks for your quick reply and your suggestion!

Unfortunately the issue remains, when the span is displayed as a block element.

It seems to relate to specific behaviour of the `iframe` of the `react-youtube` component: When a container component as suggested has a padding e.g. `padding: 10px` and the `react-youtube` component a height e.g. `100px` the elements below first jump `100px` and afterwards slide the remaining `20px` as expected.

Since I think this is tightly related to an other project and very specific, I think it is appropriate to close this issue? ;)

Keep up the excellent work, greetings!

**Comment by joshwcomeau** [comment]
Ahh, yeah, I hadn't accounted for the fact that it uses an iframe.

Sorry to hear it's causing problems, but yeah I don't have any suggestions beyond that.

Best of luck! If you do figure out a workaround, please share it here in case others encounter the same issue :)
