### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/react-flip-move#9]
In Ben Alpert's React.js Conf 2016 talk, he mentioned that animating lists is a massive priority in the coming months, especially for React Native; mobile apps often have tons and tons of lists, or are even list-based.

Despite finding it super intriguing, I have not yet had the chance to play with React Native at all.

Does anyone know if Flip Move has a place in React Native? Are there comparable tools already to accomplish the same task? Is the list-reordering thing strictly a DOM problem?

**Comment by valentinvichnal** [comment]
The Framer framework has a list ordering functionality:
http://framerjs.com/examples/preview/#list-sorting.framer

The same with react-motion:
http://chenglou.github.io/react-motion/demos/demo8-draggable-list/

I found these so far.

**Comment by joshwcomeau** [comment]
@valentinvichnal I'm familiar with that example :) Flip Move isnt actually about making the nicest animations, it's about tackling the situation of a component being handed new props, and not knowing how to animate them.

This issue is about React Native, though. Have you played with React Native at all?

**Comment by valentinvichnal** [comment]
@joshwcomeau I have not really yet, played with some backend DDP and some sortable stuff like this: https://github.com/hayeah/react-native-SortableList
This week I hope to have some time to understand React Native and how things differs.

**Comment by joshwcomeau** [comment]
I'm hoping to play around with it soon as well :) Let me know what you discover

**Comment by joshwcomeau** [comment]
Closed, because I don't have the time to explore :)
