### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by yp** [joshwcomeau/react-flip-move#97]
After updating to `v2.6.8`, the error `Uncaught TypeError: Cannot read property 'type' of undefined` is raised by function `isElementAnSFC` when one of the children is `null`/`false`/`undefined`.

I use the fact that "falsy" children are not rendered by react to let notifications (i.e., the children) appear of disappear.
Is this assumption legal in react-flip-move, too?

A possible solution of the issue (if the presence of "falsy" children is allowed in the rest of the code, like it seems) is to add the following statement at the beginning of function `isElementAnSFC`:

    if (!element) return false;

**Comment by PEM--** [comment]
Same problem for me as well.

**Comment by joshwcomeau** [comment]
Ah-ha - Hadn't anticipated that.

Will fix shortly, thanks for letting me know!

**Comment by joshwcomeau** [comment]
Fix published in `v2.6.9`
