### ISSUE TITLE
TypeError: props.children.every is not a function

### ISSUE THREAD

**Issue by alampros** [joshwcomeau/react-flip-move#99]
This looks like a regression from the latest release ([v2.6.8](https://github.com/joshwcomeau/react-flip-move/releases/tag/v2.6.8)) in the stateless functional components check.

From [v2.5.0](https://github.com/joshwcomeau/react-flip-move/releases/tag/v2.5.0) on, children were not required.

**Comment by joshwcomeau** [comment]
Fixed in `v2.6.10`. Thanks @yp!
